backend:
  name: github
  repo: abdalrahmanomairy/Daruna

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - {label: "Content", name: "body", widget: "text"}
