collections:
  - name: "data"
    label: "العقارات"
    files:
      - file: "data/properties.json"
        label: "العقارات"
        name: "properties"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "السعر", name: "price", widget: "number" }
          - { label: "المنطقة", name: "location", widget: "string" }
          - { label: "الصورة", name: "image", widget: "image" }
