backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "data"
    label: "العقارات"
    files:
      - file: "data/properties.json"
        label: "قائمة العقارات"
        name: "properties_list"
        fields:
          - label: "العقارات"
            name: "properties"
            widget: "list"
            fields:
              - { label: "العنوان", name: "title", widget: "string" }
              - { label: "السعر", name: "price", widget: "number" }
              - { label: "المنطقة", name: "location", widget: "string" }
              - { label: "الصورة", name: "image", widget: "image" }
              - { label: "الوصف", name: "description", widget: "text" }
